# Generated by Django 3.1.1 on 2021-10-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.TextField()),
                ('key', models.TextField()),
                ('SONA_code', models.TextField(default='')),
                ('get_args', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('ua_header', models.TextField(default='')),
                ('screen_width', models.TextField(default='')),
                ('screen_height', models.TextField(default='')),
                ('captcha_score', models.FloatField(blank=True, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('native_english', models.BooleanField(blank=True, null=True)),
                ('post_test_purpose', models.TextField(default='')),
                ('post_test_other', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(choices=[('IRQ', 'IRQ'), ('SENSIBILITY', 'Sensibility'), ('ENVISIONING', 'Envisioning')], max_length=11)),
                ('item_id', models.CharField(max_length=10)),
                ('version_id', models.CharField(default='', max_length=10)),
                ('condition', models.CharField(default='', max_length=10)),
                ('trial_index', models.IntegerField(blank=True, null=True)),
                ('response', models.IntegerField()),
                ('reaction_time', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affordances.participant')),
            ],
        ),
        migrations.CreateModel(
            name='FreeResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('AU', 'Alternative Uses')], max_length=2)),
                ('item_id', models.CharField(max_length=10)),
                ('version_id', models.CharField(default='', max_length=10)),
                ('condition', models.CharField(default='', max_length=10)),
                ('trial_index', models.IntegerField(blank=True, null=True)),
                ('response', models.TextField()),
                ('reaction_time', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affordances.participant')),
            ],
        ),
        migrations.CreateModel(
            name='BinaryChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('MR', 'Mental Rotation')], max_length=2)),
                ('item_id', models.CharField(max_length=10)),
                ('version_id', models.CharField(default='', max_length=10)),
                ('condition', models.CharField(default='', max_length=10)),
                ('trial_index', models.IntegerField(blank=True, null=True)),
                ('response', models.CharField(default='', max_length=10)),
                ('correct_response', models.CharField(default='', max_length=10)),
                ('is_correct', models.BooleanField()),
                ('reaction_time', models.FloatField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affordances.participant')),
            ],
        ),
    ]
