# Generated by Django 3.1.1 on 2021-10-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affordances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='version_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='version',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='rating',
            name='condition',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='rating',
            name='item_id',
            field=models.CharField(max_length=80),
        ),
    ]
