# Generated by Django 3.1.1 on 2021-10-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affordances', '0003_rating_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='rating',
            name='item_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='rating',
            name='version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
