# Generated by Django 3.1.1 on 2021-10-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affordances', '0004_auto_20211024_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binarychoice',
            name='version_id',
        ),
        migrations.AddField(
            model_name='binarychoice',
            name='item_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='binarychoice',
            name='key_press',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='binarychoice',
            name='version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='binarychoice',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
