# Generated by Django 3.1.1 on 2021-10-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affordances', '0006_binarychoice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeresponse',
            name='version_id',
        ),
        migrations.AddField(
            model_name='freeresponse',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freeresponse',
            name='item_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='freeresponse',
            name='version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='freeresponse',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='freeresponse',
            name='item_id',
            field=models.CharField(max_length=80),
        ),
    ]
